import type { Metadata } from "next";
import { Geist, Geist_Mono, Vazirmatn } from "next/font/google";
import "./globals.css";
import { ThemeModeScript } from "flowbite-react";

const vazirmatn = Vazirmatn({
  subsets: ["arabic"], // or ["latin", "arabic"]
  variable: "--font-vazirmatn", // optional for CSS variable
  weight: ["400", "700"], // pick what you need
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#0f172a" />
        <meta name="application-name" content="My App" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-title" content="My App" />
        <link rel="apple-touch-icon" href="/icons/icon-192x192.png" />
        <ThemeModeScript />
      </head>
      <body className={vazirmatn.className}>{children}</body>
    </html>
  );
}
