import type { Metadata } from "next";
import { Geist, Geist_Mono, Vazirmatn } from "next/font/google";
import "./globals.css";
import { ThemeModeScript } from "flowbite-react";

const vazirmatn = Vazirmatn({
  subsets: ["arabic"], // or ["latin", "arabic"]
  variable: "--font-vazirmatn", // optional for CSS variable
  weight: ["400", "700"], // pick what you need
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className={vazirmatn.className}>{children}</body>
    </html>
  );
}
